### ISSUE TITLE
API key information

### ISSUE THREAD

**Issue by cukabeka** [tejado/ebk-client#2]
Not sure whether I just didn't see it, but could you maybe add some info where to obtain the **app-username** and **app-password** mentioned in the readme?

**Comment by tejado** [comment]
Sorry, I can't provide any further information except the already existing one (" The smartphone apps (e.g. for Android) must include also some static/hardcoded partner account as it is using the same API"). Sadly, eBay is not offering a way to request/create these accounts. So the app is your only chance ;)

**Comment by makefu** [comment]
@cukabeka not sure if still relevant but according to https://www.sellerforum.de/ebay-de-f39/ebay-kleinanzeigen-per-schnittstelle-befuettern--t45496.html you can api credentials by contacting api@ebay-kleinanzeigen.de

cheers

**Comment by tejado** [comment]
@ciex did you tried to contact eBay over api@ebay-kleinanzeigen.de?

Otherwise the backend API credentials are in the source code of the eBay Kleinanzeigen android app, more specific in file "sources/ebk/domain/Constants.java". Use jadx (e.g. over the online decompiler http://www.javadecompilers.com) to get the source code...

**Comment by ciex** [comment]
@tejado I sent an email to that address. Will reply here if I get an answer from them!

**Comment by kurcob84** [comment]
@ciex Do you get an answer from ebay kleinanzeigen?
